export EDITOR=nvim
autoload -U +X compinit && compinit

# source ~/.goprivate
# #export $(cat ~/.env.creds|xargs)
export PAGER="less"

plugins=(git)

alias conf="nvim ~/.config/nvim/"
alias gf="cd ~/Documents/Github/"
alias ls="eza"
alias ll="eza -liR"
alias work="~/.local/bin/work"
alias lz="lazygit"
alias zz="nvim $HOME/.zshrc"
alias ref="source $HOME/.zshrc"
alias cat="bat"
alias cc="/bin/cat"
alias c="/bin/cd"
alias gr="goreleaser"
alias rm="echo Use 'rip' instead of rm."
alias cst="container-structure-test"
alias n="nvim"
alias mp="multipass"
alias getx="gnome-extensions-cli"


# tmux binds
alias ta="tmux attach-session -t"
alias tls="tmux ls"
alias tks="tmux kill-server"
alias td="tmux detach"
alias tfi="tmuxifier"
alias rn="ranger"

# This is a terrible idea
# alias kind="sudo -E kind"
# alias kubectl="sudo -E kubectl"
# alias k9s="sudo -E $HOME/.nix-profile/bin/k9s"
# alias skaffold="sudo -E /home/dhoenisch/.nix-profile/bin/skaffold"
# alias helm="sudo -E $HOME/.nix-profile/bin/helm"
# alias act="DOCKER_HOST=unix:///run/user/1000/podman/podman.sock sudo -E $HOME/.nix-profile/bin/act"



alias tt="timedatectl"
alias nf="/bin/bash $HOME/.local/bin/custom/nf"
alias oll="/bin/bash $HOME/.local/bin/oserve"
alias sp="ps aux | fzf"
zstyle ':completion:*' menu select
fpath+=~/.zfunc

# added by Webi for pyenv
eval "$(starship init zsh)"

eval "$(zoxide init --cmd cd  zsh)"


# added by Webi for pyenv
export PATH="$PATH:$HOME/.local/share/bob/nvim-bin"
export PATH="$PATH:$HOME/.tmux/plugins/tmuxifier/bin/"
export PATH="$PATH:$HOME/.local/bin"

export FZF_COMPLETION_TRIGGER='~~'

######################
# Kubernetes Configs #
######################
# export creds
# source ~/.secrets

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
eval "$(tmuxifier init -)"


# shortcut keys
list_zsh_alias() {
	local command="$HOME/.local/bin/custom/zshshortcut"
	eval $command
}

zle -N list_zsh_alias

bindkey "^A" list_zsh_alias


start_ollama() {
	local command="$HOME/.local/bin/custom/oserve"
	eval $command
}

zle -N start_ollama

bindkey "^o" start_ollama

search_open_nvim() {
	local command="$HOME/.local/bin/custom/nf"
	eval $command
}

zle -N search_open_nvim

bindkey "^f" search_open_nvim

what_script() {
	local command="$HOME/.local/bin/custom/what"
	eval $command
}

zle -N what_script

bindkey "^w" what_script

# Snippets manager

pet_search_and_run() {
	local command="$HOME/.local/bin/custom/pets"
	eval $command
}

zle -N pet_search_and_run
bindkey "^p" pet_search_and_run


# espanso reload
restart_espanso() {
	local command="espanso restart"
	eval $command
}

zle -N restart_espanso
bindkey "^e" restart_espanso


# $HOME/.local/bin/custom/tl



# Generated for pdtm. Do not edit.
export PATH=$PATH:/home/dhoenisch/.pdtm/go/bin


# Generated by Webi. Do not edit.
# eval "$(webi --init zsh)"


export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"


# Yazi Configuration
function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}


function kubectlgetall {
  for i in $(kubectl api-resources --verbs=list --namespaced -o name | grep -v "events.events.k8s.io" | grep -v "events" | sort | uniq); do
    echo "Resource:" $i

    if [ -z "$1" ]
    then
        kubectl get --ignore-not-found ${i}
    else
        kubectl -n ${1} get --ignore-not-found ${i}
    fi
  done
}

# setting for fuz
alias fuz='/home/dhoenisch/.local/bin/custom/fuz --path "/home/dhoenisch/Documents/Personal"'
alias fz='fuz --sorttime'
alias fze='fuz --edit'
alias fzd='fuz --dir-search'
export FUZ_EDITOR=nvim

eval "$(atuin init zsh)"

export PATH="$PATH:$HOME/.local/bin/custom/"
export PATH="$PATH:$HOME/.cargo/bin"
export ATAC_KEY_BINDINGS=/home/dhoenisch/.config/atac/vim_key_bindings.toml
export ATAC_MAIN_DIR=/home/dhoenisch/.config/atac/

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# go paths stuffs
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
source ~/.zsh_completions/_chx

eval "$(direnv hook zsh)"
source <(kubectl completion zsh)
