# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1


status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin
    # Aliases
    alias cat bat
    alias cd z
    alias du dust
    alias find fd
    alias ga 'git add'
    alias gc 'git commit -m'
    alias gd 'git diff'
    alias gl 'git log --oneline --graph --all'
    alias gp 'git push'
    alias grep rg
    alias gs 'git status'
    alias hack 'echo '\''Initializing cyberpunk matrix...'\'' && cmatrix -C magenta'
    alias hms 'home-manager switch'
    alias j z
    alias ls 'eza'
    alias la 'eza --long --all --git --icons'
    alias ll 'eza --long --git --icons'
    alias lz 'lazygit'
    alias ncg nix-collect-garbage
    alias neon 'echo '\''Activating neon glow...'\'' && glow $HOME/.config/fish/config.fish'
    alias nrs 'sudo nixos-rebuild switch'
    alias nsp 'nix-shell -p'
    alias ps procs
    alias top btop
    alias tree 'eza --tree --icons'
    alias n 'nvim'
    alias yy 'yazi'
    alias mp 'multipass'
    alias zz "zellij"
    alias conf "nvim ~/.config/nvim"

    # Interactive shell initialisation
    # Set up Starship prompt
    starship init fish | source

    # Initialize zoxide for fast directory navigation
    zoxide init fish | source

    # Set up fzf keybindings
    fzf --fish | source

    # Setup atuin shell history
    atuin init fish | source

    # Disable Fish greeting
    set fish_greeting

    # Set editor to Neovim
    set -gx EDITOR nvim

    # Add custom paths (e.g., for user binaries)
    fish_add_path $HOME/.local/bin/custom
    fish_add_path $HOME/.local/bin/
    fish_add_path $HOME/go/bin/
    fish_add_path $HOME/.pdtm/go/bin/

    # Cyberpunk-themed variables
    set -gx FISH_CYBERPUNK_MODE 1

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/dhoenisch/.local/share/fish/home-manager_generated_completions" $post
    end

end
eval (/home/linuxbrew/.linuxbrew/bin/brew shellenv)


# Generated for pdtm. Do not edit.
fish_add_path /home/dhoenisch/.pdtm/go/bin

# opencode
fish_add_path /home/dhoenisch/.opencode/bin
cat ~/.secrets.fish | source
direnv hook fish | source
